### ISSUE TITLE
事件机制，目前ID是string类型的，改为int会不会性能好一些？

### ISSUE THREAD

**Issue by hellojoe99** [AlianBlank/GameFrameX#10]
比如这里：
     public void Subscribe(string id, EventHandler<GameEventArgs> handler)
        {
            m_EventManager.Subscribe(id, handler);
        }

id改成int？

**Comment by hellojoe99** [comment]
因为我发现的事件ID字符串特别的长，一般是取的类名， 如HpChangeGameEventArgs,  占内存多，也有内存分配和gc的负担

**Comment by AlianBlank** [comment]
其实最开始是int 的。因为有些时候int 不好查是什么事件。所以才应了其他小伙伴的需求改成的字符串。

**Comment by AlianBlank** [comment]
一般的事件名称是EventArgs 里面定义的常量。它由于存储在常量区。不可变。所以占用的内存只有一份。所以就给开发便捷性让路了

**Comment by hellojoe99** [comment]
了解了，string也有优势 ，是我用的姿势不对
